name: 构建和发布

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 获取发布版本
        id: get_version
        run: echo "RELEASE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      
      - name: 检查发布版本
        run: echo "发布版本为 $RELEASE_VERSION"
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      
      - name: 安装依赖
        run: npm install
      
      - name: 构建项目
        run: npm run build
      
      - name: 读取发布说明
        id: read_release
        shell: bash
        run: |
          r=$(cat RELEASE.md)         
          r="${r//'%'/'%25'}"                               
          r="${r//$'\n'/'%0A'}"                             
          r="${r//$'\r'/'%0D'}"                             
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT
      
      - name: 创建 GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release v${{ env.RELEASE_VERSION }}
          body: ${{ steps.read_release.outputs.RELEASE_BODY }}
          draft: false
          prerelease: false